/* eslint-disable @typescript-eslint/no-explicit-any */
import type { PieceProperties } from './piece.types';

export const PieceInvalidProps = [
  'as',
  'kind',
  'aria',
  'withStyle',
  'direction',
  'alignContent',
  'justifyContent',
  'justifyItems',
  'alignItems',
  'display',
  'contentColumns',
  'contentRows',
  'atColumn',
  'atRow',
  'fontSize',
  'flex',
  'gap',
  'textColor',
  'backgroundColor',
  'background',
  'margin',
  'padding',
  'containerType',
  'containerName',
  'cursor',
] as (keyof PieceProperties<any, any, any>)[];
